openapi: 3.0.1
info:
  title: Products
  description: 'API to provide visible products'
  version: 1.0.0
tags:
  - name: Products
    description: Products
paths:
  /products:
    get:
      summary: Returns a string with product list available to show in grid
      operationId: getAvailableProducts
      tags:
        - products
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
              example:
                data:
                  - productsId: "5,1,3"

        400:
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 400
                message: Error in the product identifier parameter
        401:
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Credentials error or not provided
        500:
          description: Internal server error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: Unexpected server error
components:
  schemas:
    ProductResponse:
      description: Product available returned
      type: object
      properties:
        productsId:
          description: List of available product identifiers
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: HTTP response status code
        message:
          type: string
          description: Detail of error